aws_access_key                 = ""
aws_secret_key                 = ""
dockerhub_username             = ""
dockerhub_password             = ""
dockerhub_project_name_backend = ""
s3_bucket_name                 = ""