version: '3.7'
services:
  nginx:
    image: nginx:1.15-alpine
    deploy:
      resources:
        limits:
          memory: 200M
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
      - ms-ticketea-user
      - ms-ticketea-ticket
    networks:
      - nodejs-mysql-network
  frontend:
    container_name: frontend
    image: ricardovasquezpe/ticketea-frontend:latest
    ports:
      - 8080:8080
    env_file:
      - .env.frontend
    networks:
      - nodejs-mysql-network
  backend:
    container_name: backend
    image: ricardovasquezpe/ms-ticketea-gateway:latest
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 128M
    ports:
      - 3000:3000
    depends_on:
      - ms-ticketea-user
      - ms-ticketea-ticket
    environment:
      - MS_TICKET_HOST=ms-ticketea-ticket
      - MS_USER_HOST=ms-ticketea-user
    networks:
      - nodejs-mysql-network
  ms-ticketea-user:
    container_name: ms-ticketea-user
    image: ricardovasquezpe/ms-ticketea-user:latest
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - .env.backend
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ticketea
      - MYSQL_USER=root
      - MYSQL_PASSWORD=4Ev1dHzNfTK9GzG
      - TCP_HOST=ms-ticketea-user
      - MS_TICKET_TCP_HOST=ms-ticketea-ticket
    networks:
      - nodejs-mysql-network
  ms-ticketea-ticket:
    container_name: ms-ticketea-ticket
    image: ricardovasquezpe/ms-ticketea-ticket:latest
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - .env.backend
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=ticketea
      - MYSQL_USER=root
      - MYSQL_PASSWORD=4Ev1dHzNfTK9GzG
      - TCP_HOST=ms-ticketea-ticket
      - MS_USER_TCP_HOST=ms-ticketea-user
    networks:
      - nodejs-mysql-network
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: always
    environment:
      - MYSQL_DATABASE=ticketea
      - MYSQL_ROOT_PASSWORD=4Ev1dHzNfTK9GzG
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
volumes:
  mysql-data:
networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network