version: '3.7'
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
#       - "443:443"
    volumes: 
      - ./data/nginx:/etc/nginx/conf.d
#      - ./data/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    networks:
      - nodejs-mysql-network
  frontend:
    container_name: frontend
    image: ricardovasquezpe/ticketea-frontend:latest
#    build:
#      context: ../ticketea-frontend/
#      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env.frontend
    expose:
      - 8080
    networks:
      - nodejs-mysql-network
  backend:
    container_name: backend
    image: ricardovasquezpe/ticketea-backend:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
#      - 3000
      - 3000:3000
    expose:
      - 3000
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file:
      - .env.backend
#    environment:
#      - MYSQL_HOST=mysqldb
#      - MYSQL_PORT=3306
#      - MYSQL_DATABASE=ticketea
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=4Ev1dHzNfTK9GzG
    networks:
      - nodejs-mysql-network
  mysqldb:
#    image: mysql
    image: mysql:latest
#    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_DATABASE=ticketea
      - MYSQL_ROOT_PASSWORD=4Ev1dHzNfTK9GzG
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nodejs-mysql-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 3
volumes:
  mysql-data:
networks:
  nodejs-mysql-network:
    name: nodejs-mysql-network